# bomtool
# Autogenerated from man page /usr/share/man/man1/bomtool.1.gz
complete -c bomtool -l about -d 'Print the version number, the Copyright notice, and the license of the bomtoo…'
complete -c bomtool -l version -d 'Print the version number of the bomtool program to standard output and exit'
complete -c bomtool -l define-variable -d 'Define varname as value'
complete -c bomtool -l creation-time -d 'Use time as the value of the Created field in the generated SBOM instead of t…'
complete -c bomtool -l output -d 'Write the generated SBOM to file instead of standard output'

