# chdosattr
# Autogenerated from man page /usr/share/man/man1/chdosattr.1.gz
complete -c chdosattr -s R -d 'Change files and directories recursively'
complete -c chdosattr -s V -d 'Show version'
complete -c chdosattr -s H -d 'Show help'

