# copyfilerange
# Autogenerated from man page /usr/share/man/man1/copyfilerange.1.gz
complete -c copyfilerange -s r -l ranges
complete -c copyfilerange -s v -l verbose
complete -c copyfilerange -s h -l help
complete -c copyfilerange -s V -l version

