# debugedit-classify-ar
# Autogenerated from man page /usr/share/man/man1/debugedit-classify-ar.1.gz
complete -c debugedit-classify-ar -s m -l max-members -d 'Maximum number of archive members to accept'
complete -c debugedit-classify-ar -s q -l quiet -d 'Don\'t show any output (not even errors)'
complete -c debugedit-classify-ar -s v -l verbose -d 'Show extra output . SS "Help options:"'
complete -c debugedit-classify-ar -s '?' -l help -d 'Show this help message'
complete -c debugedit-classify-ar -s u -l usage -d 'Display brief usage message'
complete -c debugedit-classify-ar -s V -l version -d 'Show program version'

