# dmvdostats
# Autogenerated from man page /usr/share/man/man8/dmvdostats.8.gz
complete -c dmvdostats -s h -l help -d 'Display usage information'
complete -c dmvdostats -s v -l verbose -d 'Produce verbose output'
complete -c dmvdostats -l count -d 'Repeat the report  count times'
complete -c dmvdostats -l interval -d 'Pause  seconds between report iterations when  --count is greater than one'
complete -c dmvdostats -s o -l options -d 'Comma-separated list of fields to display'
complete -c dmvdostats -s O -l sort -d 'Comma-separated list of fields to sort by'
complete -c dmvdostats -s S -l select -d 'Display only rows that match the selection criteria'
complete -c dmvdostats -l noheadings -d 'Suppress the headings line in report output'
complete -c dmvdostats -l nosuffix -d 'Suppress the suffix on size values'
complete -c dmvdostats -l separator -d 'Use  separator between fields in report output'
complete -c dmvdostats -l units -d 'Set the display unit for size fields'

