# dpll
# Autogenerated from man page /usr/share/man/man8/dpll.8.gz
complete -c dpll -s V -l Version -d 'Print the version of the  dpll utility and exit'
complete -c dpll -s j -l json -d 'Output results in JavaScript Object Notation (JSON)'
complete -c dpll -s p -l pretty

