# extraclangtools
# Autogenerated from man page /usr/share/man/man1/extraclangtools.1.gz
complete -c extraclangtools -s p
complete -c extraclangtools -o DCMAKE_EXPORT_COMPILE_COMMANDS
complete -c extraclangtools -o fix -o header-filter
complete -c extraclangtools -l allowed_file -d 'A file containing regexes of symbol names that are not expected to be updated…'
complete -c extraclangtools -l dump_result -d 'Dump new file contents in YAML, if specified'
complete -c extraclangtools -l extra-arg -d 'Additional argument to append to the compiler command line'
complete -c extraclangtools -l extra-arg-before -d 'Additional argument to prepend to the compiler command line'
complete -c extraclangtools -l file_pattern -d 'Only rename namespaces in files that match the given regular expression patte…'
complete -c extraclangtools -s i -d 'Inplace edit <file>s, if specified'
complete -c extraclangtools -l new_namespace -d 'New namespace.  Use "" when you target the global namespace'
complete -c extraclangtools -l old_namespace -d 'Old namespace'
complete -c extraclangtools -l style -d 'The style name used for reformatting'
complete -c extraclangtools -o prefix -d 'Prepend the given path to non-absolute file paths in the header list file'
complete -c extraclangtools -o module-map-path -d 'Generate a module map and output it to the given file'
complete -c extraclangtools -o problem-files-list -d 'For use only with module map assistant'
complete -c extraclangtools -o root-module -d 'Put modules generated by the -module-map-path option in an enclosing module w…'
complete -c extraclangtools -o block-check-header-list-only -d 'Limit the #include-inside-extern-or-namespace-block check to only those heade…'
complete -c extraclangtools -o no-coverage-check -d 'Don\'t do the coverage check for a module map'
complete -c extraclangtools -o coverage-check-only -d 'Only do the coverage check for a module map'
complete -c extraclangtools -o display-file-lists -d 'Display lists of good files (no compile errors), problem files, and a combine…'
complete -c extraclangtools -o callbacks -d 'This option specifies a comma-separated list of globs describing the list of …'
complete -c extraclangtools -o output -d 'By default, pp-trace outputs the trace information to stdout'
complete -c extraclangtools -l -

