# fc-genconf
# Autogenerated from man page /usr/share/man/man1/fc-genconf.1.gz
complete -c fc-genconf -s f -l family -d 'Set a family name to generate a configuration for instead of the family name …'
complete -c fc-genconf -s g -l generic -d 'Set a generic family name to generate a configuration for instead of the gene…'
complete -c fc-genconf -s l -l lang -d 'Generate the language specific generic alias rule for'
complete -c fc-genconf -s o -l output -d 'Output a configuration into file.  default is stdout'
complete -c fc-genconf -s V -l version -d 'Show version of the program and exit'
complete -c fc-genconf -s h -l help -d 'Show summary of options'

