# find-debuginfo
# Autogenerated from man page /usr/share/man/man1/find-debuginfo.1.gz
complete -c find-debuginfo -l unique-debug-src-base
complete -c find-debuginfo -l check-elf-strict -d 'find-debuginfo will exit with a failure status'

