# fuse-overlayfs
# Autogenerated from man page /usr/share/man/man1/fuse-overlayfs.1.gz
complete -c fuse-overlayfs -s f -d 'Run in foreground'
complete -c fuse-overlayfs -s d -l debug -s o -d 'Enable debugging mode, can be very noisy'
complete -c fuse-overlayfs -s h -l help -d 'Show additional options, provided by FUSE'
complete -c fuse-overlayfs -s V -l version -d 'Show versions of fuse-overlayfs and FUSE.  DYNAMIC UID AND GID MAPPING'

