# gcore
# Autogenerated from man page /usr/share/man/man1/gcore.1.gz
complete -c gcore -s a -d 'X Item "-a" Dump all memory mappings'
complete -c gcore -s o -d 'X Item "-o prefix" The optional argument prefix specifies the prefix to be us…'
complete -c gcore -s d -d 'X Item "-d directory" Use directory as the data directory when invoking GDB f…'
complete -c gcore -l help -d 'X Item "--help"'
complete -c gcore -s h -d 'X Item "-h" . PD List all options, with brief explanations'
complete -c gcore -l version -d 'X Item "--version"'
complete -c gcore -s v -d 'Print version information and then exit.  ENVIRONMENT'

