# gdb-add-index
# Autogenerated from man page /usr/share/man/man1/gdb-add-index.1.gz
complete -c gdb-add-index -l dwarf-5 -d 'X Item "--dwarf-5" Add DWARF 5 sections instead of previous \\f(CW\\*(C`'
complete -c gdb-add-index -l help -d 'X Item "--help"'
complete -c gdb-add-index -s h -d 'X Item "-h" . PD List all options, with brief explanations'
complete -c gdb-add-index -l version -d 'X Item "--version"'
complete -c gdb-add-index -s f -s n -d OPTIONS
complete -c gdb-add-index -s v -d 'Print version information and then exit.  ENVIRONMENT'

