# gprofng-display-gmon
# Autogenerated from man page /usr/share/man/man1/gprofng-display-gmon.1.gz
complete -c gprofng-display-gmon -l version -d 'X Item "--version" Print the version number and exit'
complete -c gprofng-display-gmon -l help -d 'X Item "--help" Print usage information and exit'
complete -c gprofng-display-gmon -s o -d 'X Item "-o <exp_name>" Specify the name for the experiment directory'
complete -c gprofng-display-gmon -s O

