# hwloc-patch
# Autogenerated from man page /usr/share/man/man1/hwloc-patch.1.gz
complete -c hwloc-patch -s R -l reverse -d 'Reverse the sense the difference file'
complete -c hwloc-patch -l dry-run -d 'Check if the patch applies, but do not actually write the result'
complete -c hwloc-patch -l version -d 'Report version and exit'
complete -c hwloc-patch -s h -l help -d 'Display help message and exit.  DESCRIPTION'

