# iceauth
# Autogenerated from man page /usr/share/man/man1/iceauth.1.gz
complete -c iceauth -s f -d 'Name of the authority file to use'
complete -c iceauth -s v -d 'Turns on extra messages (verbose mode)'
complete -c iceauth -s q -d 'Turns off extra messages (quiet mode)'
complete -c iceauth -s i -d 'Ignore the locks on the authority file'
complete -c iceauth -s b -d 'Break the locks on the authority file'
complete -c iceauth -s u -d 'Print basic usage instructions'
complete -c iceauth -l help -d 'Print basic usage instructions'
complete -c iceauth -s V -d 'Print version and exit'
complete -c iceauth -l version -d 'Print version and exit USAGE When iceauth is run it will allow the following …'

