# llvm-offload-binary
# Autogenerated from man page /usr/share/man/man1/llvm-offload-binary.1.gz
complete -c llvm-offload-binary -l archive -d 'When extracting from an input binary, write all extracted images into a stati…'
complete -c llvm-offload-binary -l image -d 'Specify a set of arbitrary key-value arguments describing an image'
complete -c llvm-offload-binary -s o -d 'Write output to <file>'
complete -c llvm-offload-binary -l help -s h -d 'Display available options.  Use --help-hidden to show hidden options'
complete -c llvm-offload-binary -l help-list -d 'Display a list of all options.  Use --help-list-hidden to show hidden ones'
complete -c llvm-offload-binary -l version -d 'Display the version of the llvm-offload-binary executable'

