# llvm-ir2vec
# Autogenerated from man page /usr/share/man/man1/llvm-ir2vec.1.gz
complete -c llvm-ir2vec -l mode -d 'Specify the operation mode.  Valid values are: NDENT 7. 0'
complete -c llvm-ir2vec -s o -d 'Specify the output filename.  Use - to write to standard output (default)'
complete -c llvm-ir2vec -l help -d 'Print a summary of command line options'
complete -c llvm-ir2vec -l level -d 'Specify the embedding generation level.  Valid values are: NDENT 7. 0'
complete -c llvm-ir2vec -l function -d 'Process only the specified function instead of all functions in the module'
complete -c llvm-ir2vec -l ir2vec-kind -d 'Specify the kind of IR2Vec embeddings to generate.  Valid values are: NDENT 7'
complete -c llvm-ir2vec -l ir2vec-vocab-path -d 'Specify the path to the IR2Vec vocabulary file (required for LLVM IR embeddin…'
complete -c llvm-ir2vec -l ir2vec-opc-weight -d 'Specify the weight for opcode embeddings (default: 1. 0)'
complete -c llvm-ir2vec -l ir2vec-type-weight -d 'Specify the weight for type embeddings (default: 0. 5)'
complete -c llvm-ir2vec -l ir2vec-arg-weight -d 'Specify the weight for argument embeddings (default: 0. 2)'
complete -c llvm-ir2vec -l mir2vec-vocab-path -d 'Specify the path to the MIR2Vec vocabulary file (required for Machine IR embe…'
complete -c llvm-ir2vec -l mir2vec-kind -d 'Specify the kind of MIR2Vec embeddings to generate'
complete -c llvm-ir2vec -l mir2vec-opc-weight -d 'Specify the weight for machine opcode embeddings (default: 1. 0)'
complete -c llvm-ir2vec -l mir2vec-common-operand-weight -d 'Specify the weight for common operand embeddings (default: 1. 0)'
complete -c llvm-ir2vec -l mir2vec-reg-operand-weight -d 'Specify the weight for register operand embeddings (default: 1. 0)'

