# lsdosattr
# Autogenerated from man page /usr/share/man/man1/lsdosattr.1.gz
complete -c lsdosattr -s R -d 'List subdirectories recursively'
complete -c lsdosattr -s a -d 'Do not ignore entries starting with a dot(\'. \')'
complete -c lsdosattr -s d -d 'List directories themselves, not their contents'
complete -c lsdosattr -s l -d 'Use long attribute names instead of single character abbreviations'
complete -c lsdosattr -s V -d 'Show version'
complete -c lsdosattr -s h -d 'Show help'

