# lua5.4
# Autogenerated from man page /usr/share/man/man1/lua5.4.1.gz
complete -c 'lua5.4' -s e -d 'execute statement R stat '
complete -c 'lua5.4' -s i -d 'enter interactive mode after executing R script '
complete -c 'lua5.4' -s l -d 'require library  mod into global R mod '
complete -c 'lua5.4' -s v -d 'show version information'
complete -c 'lua5.4' -s E -d 'ignore environment variables'
complete -c 'lua5.4' -s W -d 'turn warnings on'

