# mkfs.exfat
# Autogenerated from man page /usr/share/man/man8/mkfs.exfat.8.gz
complete -c 'mkfs.exfat' -s b -l boundary-align -d 'Specifies the alignment for the FAT and the start of the cluster heap'
complete -c 'mkfs.exfat' -s s -l sector-size -d 'Specifies the sector size of the exFAT file system'
complete -c 'mkfs.exfat' -s c -l cluster-size -d 'Specifies the cluster size of the exFAT file system'
complete -c 'mkfs.exfat' -s f -l full-format -d 'Performs a full format'
complete -c 'mkfs.exfat' -s F -l force -d 'Allow overwriting a device that already contains a disk signature'
complete -c 'mkfs.exfat' -s K -l no-discard -d 'Do not attempt to discard blocks'
complete -c 'mkfs.exfat' -s P -l partition-table -d 'Specifies the type of partition table to set up'
complete -c 'mkfs.exfat' -l bootcode-msg -d 'Specifies the message the x86 real mode MBR bootstrap program displays'
complete -c 'mkfs.exfat' -s C -l verify-written -d 'Verify filesystem metadata by reading it back after writing'
complete -c 'mkfs.exfat' -s h -l help -d 'Prints the help and exit'
complete -c 'mkfs.exfat' -s L -l volume-label -d 'Specifies the volume label to be associated with the exFAT filesystem'
complete -c 'mkfs.exfat' -s U -l volume-guid -d 'Specifies the volume GUID to be associated with the exFAT filesystem'
complete -c 'mkfs.exfat' -l pack-bitmap -d 'Attempts to relocate the exFAT allocation bitmap so that it ends at the align…'
complete -c 'mkfs.exfat' -l upcase -d 'Format the volume with the specified up-case table file in binary format'
complete -c 'mkfs.exfat' -s q -l quiet -d 'Prints only error messages while creating the exFAT filesystem'
complete -c 'mkfs.exfat' -s v -l verbose -d 'Prints verbose debugging information while creating the exFAT filesystem'
complete -c 'mkfs.exfat' -s t -d option
complete -c 'mkfs.exfat' -s V -l version -d 'Prints the version number and exits.  SEE ALSO mkfs (8), mount (8), mkfs'

