# netcap
# Autogenerated from man page /usr/share/man/man8/netcap.8.gz
complete -c netcap -l advanced -d 'Enable the posture/tree view'
complete -c netcap -l interface -d 'With --advanced, limit the report to the named interface'
complete -c netcap -l list-interfaces -d 'With --advanced, list the current network namespace interface names instead o…'
complete -c netcap -l json -d 'With --advanced, emit machine-readable JSON instead of the tree view'
complete -c netcap -l no-color -d 'Suppress colored output'

