# nfsdctl
# Autogenerated from man page /usr/share/man/man8/nfsdctl.8.gz
complete -c nfsdctl -l help -d 'nfsdctl listener --help OPTIONS'
complete -c nfsdctl -s d -l debug
complete -c nfsdctl -s h
complete -c nfsdctl -s s -l syslog
complete -c nfsdctl -s V -l version
complete -c nfsdctl -s m -l min-threads -d '    If set to a positive, non-zero value, then dynamic threading is enabled f…'
complete -c nfsdctl -s k -l fh-key-file -d '    If set to the path of a file, use the first 128 bits of the sha1 hash    …'

