# pccritic
# Autogenerated from man page /usr/share/man/man1/pccritic.1.gz
complete -c pccritic -l about -d 'Print the version number, the Copyright notice, and the license of the pccrit…'
complete -c pccritic -l version -d 'Print the version number of the pccritic program to standard output and exit'
complete -c pccritic -l help -d 'Print a short usage summary to standard output and exit'
complete -c pccritic -l quiet -d 'Print only the score and grade for each target, one per line, instead of the …'
complete -c pccritic -l min-score -d 'Exit with a non-zero status if any target scores below n'
complete -c pccritic -l color -d 'Control colorized output.  when may be auto (the default), always, or never'
complete -c pccritic -l define-variable -d 'Define varname as value'

