# spdxtool
# Autogenerated from man page /usr/share/man/man1/spdxtool.1.gz
complete -c spdxtool -l about -d 'Print the version number, the Copyright notice, and the license of the spdxto…'
complete -c spdxtool -l version -d 'Print the version number of the spdxtool program to standard output and exit'
complete -c spdxtool -l agent-name -d 'Set agent name-property in /Core/Agent-class.  Default is \'Default\''
complete -c spdxtool -l creation-time -d 'Set create-property time in /Core/CreationInfo-class'
complete -c spdxtool -l creation-id -d 'Set creation ID in /Core/CreationInfoc-class'
complete -c spdxtool -l define-variable -d 'Define varname as value'

