# storagectl
# Autogenerated from man page /usr/share/man/man1/storagectl.1.gz
complete -c storagectl -l system -d 'Operate on system-wide storage providers'
complete -c storagectl -l user -d 'Operate on per-user storage providers'
complete -c storagectl -l json -d 'Shows output formatted as JSON'
complete -c storagectl -l no-pager -d 'Do not pipe output into a pager'
complete -c storagectl -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c storagectl -l no-ask-password -d 'Do not query the user for authentication for privileged operations'
complete -c storagectl -s h -l help -d 'Print a short help text and exit'
complete -c storagectl -l version -d 'Print a short version string and exit'
complete -c storagectl -s o -d 'mount options are forwarded to mount.  In addition, the following "storage'

