# systemd-storage-fs@.service
# Autogenerated from man page /usr/share/man/man8/systemd-storage-fs@.service.8.gz
complete -c 'systemd-storage-fs@.service' -l system -d 'Operate in system mode.  Volumes are stored below /var/lib/storage/'
complete -c 'systemd-storage-fs@.service' -l user -d 'Operate in user mode.  Volumes are stored below $XDG_STATE_HOME/storage/'
complete -c 'systemd-storage-fs@.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-storage-fs@.service' -l version -d 'Print a short version string and exit'

