# systemd-ssh-issue
# Autogenerated from man page /usr/share/man/man1/systemd-ssh-issue.1.gz
complete -c systemd-ssh-issue -l issue-path -d 'Changes the path to the issue file to write to/remove'
complete -c systemd-ssh-issue -s h -l help -d 'Print a short help text and exit'
complete -c systemd-ssh-issue -l version -d 'Print a short version string and exit'

