# systemd-storage-block@.service
# Autogenerated from man page /usr/share/man/man8/systemd-storage-block@.service.8.gz
complete -c 'systemd-storage-block@.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-storage-block@.service' -l version -d 'Print a short version string and exit'

