# systemd-sysinstall
# Autogenerated from man page /usr/share/man/man8/systemd-sysinstall.8.gz
complete -c systemd-sysinstall -l definitions -d 'Overrides the directory where systemd-repart shall read its partition definit…'
complete -c systemd-sysinstall -l welcome -d 'Takes a boolean argument'
complete -c systemd-sysinstall -l chrome -d 'Takes a boolean argument'
complete -c systemd-sysinstall -l erase -d 'Takes a boolean argument'
complete -c systemd-sysinstall -l confirm -d 'Takes a boolean argument'
complete -c systemd-sysinstall -l reboot -d 'Takes a boolean argument'
complete -c systemd-sysinstall -l variables -d 'Takes a boolean argument'
complete -c systemd-sysinstall -l summary -d 'Takes a boolean argument'
complete -c systemd-sysinstall -l kernel -d 'Takes a path to a unified kernel image (UKI)'
complete -c systemd-sysinstall -l set-credential -d 'Accepts an additional system credential to encrypt (with a key generated on t…'
complete -c systemd-sysinstall -l load-credential -d 'Similar to --set-credential= but reads the credential value from a file on di…'
complete -c systemd-sysinstall -l copy-locale -l copy-keymap -l copy-timezone -d 'These options take boolean parameters'
complete -c systemd-sysinstall -l mute-console -d 'Takes a boolean argument'
complete -c systemd-sysinstall -s h -l help -d 'Print a short help text and exit'
complete -c systemd-sysinstall -l version -d 'Print a short version string and exit'

