# systemd-report
# Autogenerated from man page /usr/share/man/man1/systemd-report.1.gz
complete -c systemd-report -l system -l user -d 'Query per-system metrics sources (the default), or the per-user metrics sourc…'
complete -c systemd-report -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-report -l json -d 'Shows output formatted as JSON'
complete -c systemd-report -s j -d 'Equivalent to --json=pretty if running on a terminal, and --json=short otherw…'
complete -c systemd-report -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c systemd-report -s h -l help -d 'Print a short help text and exit'
complete -c systemd-report -l version -d 'Print a short version string and exit'
complete -c systemd-report -l url -d 'Upload the collected report to the specified address instead of writing it to…'
complete -c systemd-report -l key -d 'Takes a path to a SSL key file in PEM format, used for client certificate aut…'
complete -c systemd-report -l cert -d 'Takes a path to a SSL certificate file in PEM format, used for client certifi…'
complete -c systemd-report -l trust -d 'Takes a path to a SSL CA certificate file in PEM format used to verify the se…'
complete -c systemd-report -l network-timeout -d 'Timeout for the network upload operation'
complete -c systemd-report -l extra-header -d 'Inject an additional HTTP header into the upload request'

