# systemd-imds
# Autogenerated from man page /usr/share/man/man1/systemd-imds.1.gz
complete -c systemd-imds -l well-known -d 'switch) general IMDS service data and a few well known fields are displayed i…'
complete -c systemd-imds -l userdata -d 'option specified (see below) the "userdata" provided via IMDS is written to s…'
complete -c systemd-imds -l import -d 'option specified, various well known and userdata fields are imported into th…'
complete -c systemd-imds -s K
complete -c systemd-imds -l refresh
complete -c systemd-imds -l cache
complete -c systemd-imds -s u
complete -c systemd-imds -s h -l help
complete -c systemd-imds -l version

