# xargs
# Autogenerated from man page /usr/share/man/man1/xargs.1.gz
complete -c xargs -s 0 -d 'TQ  --null Input items are terminated by a null character instead of by white…'
complete -c xargs -l delimiter -d 'TQ  -d\\*(~~ delim Input items are terminated by the specified character'
complete -c xargs -s o -d 'TQ  --open-tty Reopen standard input as  /dev/tty in the child process before…'
complete -c xargs -s p -d 'TQ  --interactive Prompt the user about whether to run each command line and …'
complete -c xargs -l process-slot-var -d 'Set the environment variable  name to a unique value in each running child pr…'
complete -c xargs -s r -d 'TQ  --no-run-if-empty If the standard input does not contain any nonblanks, d…'
complete -c xargs -l show-limits -d 'Display the limits on the command-line length which are imposed by the operat…'
complete -c xargs -s t -d 'TQ  --verbose Print the command line on the standard error output before exec…'
complete -c xargs -s x -d 'TQ  --exit Exit if the size (see the  -s option) is exceeded'
complete -c xargs -l help -d 'Print a summary of the options to  xargs and exit'
complete -c xargs -s n -d and
complete -c xargs -s L -d 'options are used)'
complete -c xargs -s P -d option
complete -c xargs -o print0 -d 'option does this for you'
complete -c xargs -l null -d 'Input items are terminated by a null character instead of by whitespace, and …'
complete -c xargs -s a
complete -c xargs -l arg-file -d 'Read items from file instead of standard input'
complete -c xargs -s d -d 'Input items are terminated by the specified character'
complete -c xargs -s E -d 'Set the end-of-file string to eof-str '
complete -c xargs -s e -d 'is used, no end-of-file string is used'
complete -c xargs -l eof -d 'This option is a synonym for the'
complete -c xargs -s I -d 'Replace occurrences of replace-str in the initial-arguments with names read f…'
complete -c xargs -s i
complete -c xargs -l replace -d 'This option is a synonym for'
complete -c xargs -s l
complete -c xargs -l max-lines -d 'Synonym for the'
complete -c xargs -l max-args -d 'Use at most max-args arguments per command line'
complete -c xargs -s s -d 'option) is exceeded, unless the'
complete -c xargs -l max-procs -d 'Run up to max-procs processes at a time; the default is 1'
complete -c xargs -l open-tty -d 'Reopen standard input as /dev/tty in the child process before executing the c…'
complete -c xargs -l interactive -d 'Prompt the user about whether to run each command line and read a line from t…'
complete -c xargs -l no-run-if-empty -d 'If the standard input does not contain any nonblanks, do not run the command'
complete -c xargs -l max-chars -d 'Use at most max-chars characters per command line, including the command and …'
complete -c xargs -l verbose -d 'Print the command line on the standard error output before executing it'
complete -c xargs -l exit -d 'Exit if the size (see the'
complete -c xargs -l mycommand -d 'instead of rejecting this as unrecognized option'
complete -c xargs -l version -d 'Print the version number of xargs and exit.  The options'
complete -c xargs -o n1c -d ') is ignored after the'

