# xfs_healer
# Autogenerated from man page /usr/share/man/man8/xfs_healer.8.gz
complete -c xfs_healer -l everything -d 'Ask the kernel to send us good metadata health events, not only events relate…'
complete -c xfs_healer -l foreground -d 'Start enough event handling threads to allow consumption of all online CPUs'
complete -c xfs_healer -l no-autofsck -d 'Do not use the  autofsck filesystem property to decide whether or not to repa…'
complete -c xfs_healer -l quiet -d 'Do not print every event to standard output'
complete -c xfs_healer -l repair -d 'Always try to repair each piece of corrupt metadata when the kernel tells us …'
complete -c xfs_healer -l supported -d 'Check if the filesystem supports sending health events'
complete -c xfs_healer -s V -d 'Prints the version number and exit'

