# xfs_healer_start
# Autogenerated from man page /usr/share/man/man8/xfs_healer_start.8.gz
complete -c xfs_healer_start -l supported -d 'Check if the kernel supports listening for mount events'
complete -c xfs_healer_start -l mountns -d 'Monitor the given mount namespace'
complete -c xfs_healer_start -s V -d 'Prints the version number and exit.  SEE ALSO xfs_healer (8)'

